# Generated by Django 5.2.2 on 2025-06-08 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short description of the task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task.')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='ongoing', help_text='Current status of the task.', max_length=10)),
                ('due_date', models.DateField(blank=True, help_text='Optional due date for the task.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='The user currently assigned to this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='The group this task belongs to (optional for personal tasks).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.group')),
                ('owner', models.ForeignKey(help_text='The user who created this task.', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
